In [2]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv("loan.csv")

In [5]:
df

age  gender    occupation education_level marital_status  income  \
0    32    Male      Engineer      Bachelor's        Married   85000   
1    45  Female       Teacher        Master's         Single   62000   
2    28    Male       Student     High School         Single   25000   
3    51  Female       Manager      Bachelor's        Married  105000   
4    36    Male    Accountant      Bachelor's        Married   75000   
..  ...     ...           ...             ...            ...     ...   
56   39    Male     Architect        Master's        Married  100000   
57   25  Female  Receptionist     High School         Single   32000   
58   43    Male        Banker      Bachelor's        Married   95000   
59   30  Female        Writer        Master's         Single   55000   
60   38    Male          Chef     Associate's        Married   65000   

    credit_score loan_status  
0            720    Approved  
1            680    Approved  
2            590      Denied  
3            780    Approved  
4            710    Approved  
..           ...         ...  
56           770    Approved  
57           570      Denied  
58           760    Approved  
59           650    Approved  
60           700    Approved  

[61 rows x 8 columns]

In [6]:
df.head()

age  gender  occupation education_level marital_status  income  \
0   32    Male    Engineer      Bachelor's        Married   85000   
1   45  Female     Teacher        Master's         Single   62000   
2   28    Male     Student     High School         Single   25000   
3   51  Female     Manager      Bachelor's        Married  105000   
4   36    Male  Accountant      Bachelor's        Married   75000   

   credit_score loan_status  
0           720    Approved  
1           680    Approved  
2           590      Denied  
3           780    Approved  
4           710    Approved

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   age              61 non-null     int64 
 1   gender           61 non-null     object
 2   occupation       61 non-null     object
 3   education_level  61 non-null     object
 4   marital_status   61 non-null     object
 5   income           61 non-null     int64 
 6   credit_score     61 non-null     int64 
 7   loan_status      61 non-null     object
dtypes: int64(3), object(5)
memory usage: 3.9+ KB


In [9]:
df.describe()

age         income  credit_score
count  61.000000      61.000000     61.000000
mean   37.081967   78983.606557    709.836066
std     8.424755   33772.025802     72.674888
min    24.000000   25000.000000    560.000000
25%    30.000000   52000.000000    650.000000
50%    36.000000   78000.000000    720.000000
75%    43.000000   98000.000000    770.000000
max    55.000000  180000.000000    830.000000

In [12]:
df.isnull().sum()

age                0
gender             0
occupation         0
education_level    0
marital_status     0
income             0
credit_score       0
loan_status        0
dtype: int64

In [16]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler


In [17]:
le=LabelEncoder()

In [18]:
categorical_columns=["gender", "occupation", "education_level", "marital_status", "loan_status"]

In [20]:
for col in categorical_columns:
    df[col]=le.fit_transform(df[col])

In [23]:
X=df.drop(columns="loan_status")
y=df["loan_status"]

In [29]:
scaler = StandardScaler()
X[['income', 'credit_score']] = scaler.fit_transform(X[['income', 'credit_score']])


In [30]:
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.2, random_state=42)

In [34]:
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier, HistGradientBoostingClassifier, BaggingClassifier

In [36]:
from sklearn.tree import DecisionTreeClassifier

In [39]:
from sklearn.linear_model import LogisticRegression

In [40]:
from sklearn.svm import SVC

In [43]:
from xgboost.xgbclassifier import XGBClassifier

ModuleNotFoundError: No module named 'xgboost'

In [44]:
pip install xgboost

Defaulting to user installation because normal site-packages is not writeable
  Obtaining dependency information for xgboost from https://files.pythonhosted.org/packages/fe/df/e3a1f3f008db8d2b199ded2168014c7784b8027714b74d802c892815fd72/xgboost-2.1.2-py3-none-win_amd64.whl.metadata
   ---------------------------------------- 0.0/124.9 MB ? eta -:--:--
   ---------------------------------------- 0.5/124.9 MB 10.2 MB/s eta 0:00:13
   ---------------------------------------- 1.1/124.9 MB 11.7 MB/s eta 0:00:11
   ---------------------------------------- 1.5/124.9 MB 10.5 MB/s eta 0:00:12
   ---------------------------------------- 1.6/124.9 MB 9.0 MB/s eta 0:00:14
   ---------------------------------------- 1.6/124.9 MB 9.0 MB/s eta 0:00:14
    --------------------------------------- 2.5/124.9 MB 9.3 MB/s eta 0:00:14
    --------------------------------------- 2.5/124.9 MB 8.0 MB/s eta 0:00:16
    --------------------------------------- 3.0/124.9 MB 8.2 MB/s eta 0:00:15
   - --------------

In [45]:
from xgboost import XGBClassifier

In [50]:
 pip install lightgbm

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [51]:
pip install catboost

Defaulting to user installation because normal site-packages is not writeable
  Obtaining dependency information for catboost from https://files.pythonhosted.org/packages/1c/e1/78e635a1e5f0066bd02a1ecfd658ad09fe30d275c65c2d0dd76fe253e648/catboost-1.2.7-cp311-cp311-win_amd64.whl.metadata
  Obtaining dependency information for graphviz from https://files.pythonhosted.org/packages/00/be/d59db2d1d52697c6adc9eacaf50e8965b6345cc143f671e1ed068818d5cf/graphviz-0.20.3-py3-none-any.whl.metadata
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB 9.6 MB/s eta 0:00:11
   ---------------------------------------- 1.1/101.7 MB 13.7 MB/s eta 0:00:08
    --------------------------------------- 1.6/101.7 MB 12.5 MB/s eta 0:00:08
    --------------------------------------- 2.1/101.7 MB 13.1 MB/s eta 0:00:08
    --------------------------------------- 2.4/101.7 MB 11.6 MB/s eta 0:00:09
   - -------------------------------------- 2

In [53]:
from lightgbm import LGBMClassifier

In [54]:
from catboost import CatBoostClassifier

In [56]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [68]:
models={
    "Random_forest": RandomForestClassifier(random_state=42),
    "GradientBoosting": GradientBoostingClassifier(random_state=42),
    
    
    "AdaBoost": AdaBoostClassifier(random_state=42),
    "HistGradientBoosting": HistGradientBoostingClassifier(random_state=42),
    "Bagging": BaggingClassifier(random_state=42),
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "Logistic Regression": LogisticRegression(random_state=42),
    "SVM": SVC(random_state=42),
    "XGBoost": XGBClassifier(random_state=42),
    "LightGBM": LGBMClassifier(random_state=42, verbose=-1),
    "CatBoost": CatBoostClassifier(random_state=42, verbose=False)

}

In [70]:
for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred=model.predict(X_test)
    accuracy=accuracy_score(y_test, y_pred)
    
    print(f"{name}:{accuracy}")
    print(f"Confusion Matrix: \n{confusion_matrix(y_test, y_pred)}")
    print(f"Classification Report: {classification_report(y_test, y_pred)}")
    print("-----------------------------------------------------")

Random_forest:0.9230769230769231
Confusion Matrix: 
[[8 1]
 [0 4]]
Classification Report:               precision    recall  f1-score   support

           0       1.00      0.89      0.94         9
           1       0.80      1.00      0.89         4

    accuracy                           0.92        13
   macro avg       0.90      0.94      0.92        13
weighted avg       0.94      0.92      0.93        13

-----------------------------------------------------
GradientBoosting:1.0
Confusion Matrix: 
[[9 0]
 [0 4]]
Classification Report:               precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       1.00      1.00      1.00         4

    accuracy                           1.00        13
   macro avg       1.00      1.00      1.00        13
weighted avg       1.00      1.00      1.00        13

-----------------------------------------------------
AdaBoost:0.9230769230769231
Confusion Matrix: 
[[8 1]
 [0 4]]
Classifi